; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
; else it does not compile
lib_compat_mode = strict
lib_deps =
    chandrawi/LoRaRF@^2.1.1
; Used for the OTA to use async webserver, gain more performance
build_flags=
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-DELEGANTOTA_DEBUG=1
	-DUPDATE_DEBUG=1

[env:native]
platform = native
test_build_src = false
build_flags =
    -std=c++17
    -Itest/native
    -DUNIT_TEST
