; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
; else it does not compile
lib_compat_mode = strict
lib_deps =
    chandrawi/LoRaRF@^2.1.1

; Configuration des flags de compilation (OTA + Activation USB Natif)
build_flags=
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-DELEGANTOTA_DEBUG=1
	-DUPDATE_DEBUG=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Serial Monitor configuration
;monitor_port = COM5
monitor_speed = 115200