[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[tool.isort]
profile = "black"
known_first_party = [
    "GPIO",
    "a_config_loader",
    "arena",
    "avoidance",
    "boombot_strategy",
    "brains",
    "common",
    "controllers",
    "debug_functions",
    "geometry",
    "led_strip",
    "navigation",
    "navigator",
    "path_planner",
    "rasp",
    "remote",
    "robot1",
    "sensors",
    "strategies",
    "strategy",
    "sub_graphs",
    "tasks",
    "teensy",
    "trajectory_planner",
    "usb_com",
    "utils",
    "video",
]
skip_glob = [
    "**/common/navigation/avoidance/__init__.py",
    "**/common/navigation/path_planner/__init__.py",
    "**/robot1/rasp/controllers/actuators/__init__.py",
]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
plugins = "mypy-type-checker"
pretty = true
python_version = "3.13"
show_error_codes = true
strict = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = false

[tool.pydoclint]
allow-init-docstring = true
baseline = "pydoclint-baseline.txt"
check-style-mismatch = true
generate-baseline = true
show-filenames-in-every-violation-message = true
skip-checking-short-docstrings = false
style = 'google'

[tool.pylint.main]
enable = "all"
disable = [
    "E0401", # import-error
    "R0902", # too-many-instance-attributes
    "R0903", # too-few-public-methods
    "W0212", # protected-access -> Best management with ruff
    "W0613", # unused-argument -> Best management with ruff
    "W1113", # keyword-arg-before-vararg -> Best management with ruff
]
msg-template = "{line}:{column}: {msg_id}: {msg} ({symbol})"
output-format = "text"

[tool.ruff]
exclude = ["*.ipynb"]
fix = true
indent-width = 4
line-length = 88
output-format = "grouped"
preview = true
show-fixes = true
target-version = "py313"
unsafe-fixes = false

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

[tool.ruff.lint.isort]
known-first-party = [
    "GPIO",
    "a_config_loader",
    "arena",
    "avoidance",
    "boombot_strategy",
    "brains",
    "common",
    "controllers",
    "debug_functions",
    "geometry",
    "led_strip",
    "navigation",
    "navigator",
    "path_planner",
    "rasp",
    "remote",
    "robot1",
    "sensors",
    "strategies",
    "strategy",
    "sub_graphs",
    "tasks",
    "teensy",
    "trajectory_planner",
    "usb_com",
    "utils",
    "video",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "CPY001",  # missing-copyright-notice
    "D103",    # missing-module-docstring -> temporaire
    "E501",    # line-too-long -> temporaire le temps de faire le reste
    "ERA001",  # commented-out-code -> temporaire
    "FBT001",  # boolean-type-hint-positional-argument -> temporaire
    "FBT002",  # boolean-default-value-positional-argument -> temporaire
    "FIX002",  # line-contains-todo
    "FIX004",  # line-contains-hack
    "G004",    # logging-f-string
    "PLR0917", # too-many-positional-arguments
    "PLR0913", # too-many-arguments
    "TD001",   # invalid-todo-tag
    "TD002",   # missing-todo-author
    "TD003",   # missing-todo-link
]

[tool.ruff.lint.pydocstyle]
convention = "google"
