from navigation.debug_functions.speed_profile import test_speed_profile
from navigation.debug_functions.trajectory_planer import test_trajectory_planning
from navigation.debug_functions.navigator import test_navigator_execution
