import numpy as np

arena_elements = {
    "starting_zone": {
        "blue": {
            "id_zone": 1,
            "position": np.array([0.000, 0.000]),
            "width": 0.6,
            "height": 0.45,
            "color": "#1E90FF",
        },
        "yellow": {
            "id_zone": 0,
            "position": np.array([2.400, 0.000]),
            "width": 0.6,
            "height": 0.45,
            "color": "#FFD700",
        },
    },
    "zone_depot": [
        {
            "id_zone": 12,
            "position": np.array([2.200, 1.800]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 20,
            "position": np.array([1.400, 1.800]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 16,
            "position": np.array([0.600, 1.800]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 11,
            "position": np.array([2.800, 1.100]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 14,
            "position": np.array([2.100, 1.100]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 19,
            "position": np.array([1.400, 1.100]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 18,
            "position": np.array([0.700, 1.100]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 15,
            "position": np.array([0.000, 1.100]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 13,
            "position": np.array([1.650, 0.450]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
        {
            "id_zone": 17,
            "position": np.array([1.150, 0.450]),
            "width": 0.2,
            "height": 0.2,
            "color": "#295E24",
        },
    ],
    "zone_ramassage": [
        {
            "id_zone": 7,
            "position": np.array([0.100, 0.700]),
            "width": 0.15,
            "height": 0.2,
            "color": "#EFAF00",
        },
        {
            "id_zone": 8,
            "position": np.array([0.100, 1.500]),
            "width": 0.15,
            "height": 0.2,
            "color": "#EFAF00",
        },
        {
            "id_zone": 3,
            "position": np.array([2.750, 0.700]),
            "width": 0.15,
            "height": 0.2,
            "color": "#EFAF00",
        },
        {
            "id_zone": 4,
            "position": np.array([2.750, 1.500]),
            "width": 0.15,
            "height": 0.2,
            "color": "#EFAF00",
        },
        {
            "id_zone": 10,
            "position": np.array([1.050, 1.125]),
            "width": 0.2,
            "height": 0.15,
            "color": "#EFAF00",
        },
        {
            "id_zone": 6,
            "position": np.array([1.750, 1.125]),
            "width": 0.2,
            "height": 0.15,
            "color": "#EFAF00",
        },
        {
            "id_zone": 9,
            "position": np.array([1.000, 1.725]),
            "width": 0.2,
            "height": 0.15,
            "color": "#EFAF00",
        },
        {
            "id_zone": 5,
            "position": np.array([1.800, 1.725]),
            "width": 0.2,
            "height": 0.15,
            "color": "#EFAF00",
        },
    ],
}
