# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint + Test

on:
  push:
    branches: [ "dev", "dev-preshot" ]
  pull_request:
    branches: [ "competition", "dev"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f rasp/requirements.txt ]; then pip install -r rasp/requirements.txt; fi
    - name: Lint with flake8
      run: | 
        cd rasp
        flake8 .
    - name: Test with pytest
      run: |
        pytest .

